name: debwouya_market
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  responsive_sizer: ^3.3.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.8
  image_cropper: ^6.0.0
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  pin_code_fields: ^8.0.1
  internet_connection_checker: ^1.0.0+1
  shimmer: ^3.0.0
  country_picker: ^2.0.26
  google_nav_bar: ^5.0.6
  flutter_html:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
          weight: 700

